-- Описание структуры: у каждого человека есть машина.
-- Причем несколько человек могут пользоваться одной машиной.
-- У каждого человека есть имя, возраст и признак того,
-- что у него есть права (или их нет).
-- У каждой машины есть марка, модель и стоимость.
-- Также не забудьте добавить таблицам первичные ключи и связать их.

CREATE TABLE Cars
(
    id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    make  varchar(50),
    model varchar(50),
    price numeric
);

CREATE TABLE Drivers
(
    id                 int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name               varchar(50),
    age                int,
    has_driver_license bool,
    car_id             int REFERENCES Cars (id)
);